name: Ophidian Publish
description: Publish Ophidian-based Plugin with PNPM

branding:
  icon: aperture
  color: purple

inputs:
  token:
    description: Github Token (for release publishing)
    required: true
  release-notes:
    description: Markdown for release notes (e.g. github.event.commits[0].message)
    required: true
  node-version:
    description: Desired version of Node.js
    default: "14.x"
    required: true
  package-manager:
    description: Desired package manager (npm, pnpm, or yarn)
    default: pnpm
    required: true
  pnpm-version:
    description: Desired version of pnpm
    default: "6.32.19"
    required: true

runs:
  using: composite

  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.package-manager }}

    - uses: pnpm/action-setup@v2.2.2
      if: ${{ inputs.package-manager == 'pnpm' }}
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Create release and Upload
      id: release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        COMMIT_MESSAGE: ${{ inputs.release-notes }}
        PACKAGER: ${{ inputs.package-manager }}
      run: |
        "$GITHUB_ACTION_PATH"/publish-plugin.sh
