name: Ophidian Publish
description: Publish Ophidian-based Plugin with PNPM

branding:
  icon: aperture
  color: purple

inputs:
  token:
    description: Github Token (for release publishing)
    required: true
  release-notes:
    description: Markdown for release notes (e.g. github.event.commits[0].message)
    required: true
  node-version:
    description: Desired version of Node.js
    default: "22.x"
    required: true
  build-script:
    description: package.json script to run (defaults to 'build')
    default: build
    required: true
  pnpm-version:
    description: Desired version of pnpm
    default: "7.33.6"
    required: true

runs:
  using: composite

  steps:
    - shell: bash
      run: npm i -g --force corepack && corepack enable

    - uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Build artifacts
      id: build
      shell: bash
      env:
        COMMIT_MESSAGE: ${{ inputs.release-notes }}
        PACKAGER: ${{ inputs.package-manager }}
        BUILD_SCRIPT: ${{ inputs.build-script }}
      run: |
        "$GITHUB_ACTION_PATH"/publish-plugin.sh

    - name: Attest build artifacts
      uses: actions/attest@v4
      with:
        subject-path: |
          main.js
          ${{ steps.build.outputs.styles }}

    - name: Create release
      shell: bash
      env:
          GITHUB_TOKEN: ${{ inputs.token }}
          COMMIT_MESSAGE: ${{ inputs.release-notes }}
      run: |
          export TAG_NAME="${GITHUB_REF#refs/tags/}"
          gh release create "$TAG_NAME" -t "$TAG_NAME" -n "### $COMMIT_MESSAGE" -d \
            main.js manifest.json ${{ steps.build.outputs.styles }}
