name: Publish to NPM

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "[0-9]*" # Only push numbered versions to npm

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
